---

- hosts: debian
  tasks:
    - name: Ensure a locale exists
      community.general.locale_gen:
        - name: en_US ISO-8859-1
          state: present
        - name: en_US.ISO-8859-15 ISO-8859-15
          state: present
        - name: en_US.UTF-8 UTF-8
          state: present